let CATALOG = [
	{
		id: 't11',
		name: 'Прямоугольный треугольник',
		color: 'Белый',
		img: 'images/goods/triangle1_1.jpg',
		price: 1200,
	},
	{
		id: 't12',
		name: 'Прямоугольный треугольник',
		color: 'Красный',
		img: 'images/goods/triangle1_2.jpg',
		price: 1200,
	},
	{
		id: 't13',
		name: 'Прямоугольный треугольник',
		color: 'Желтый',
		img: 'images/goods/triangle1_3.jpg',
		price: 1200,
	},
	{
		id: 't14',
		name: 'Прямоугольный треугольник',
		color: 'Зеленый',
		img: 'images/goods/triangle1_4.jpg',
		price: 1200,
	},
	{
		id: 't15',
		name: 'Прямоугольный треугольник',
		color: 'Голубой',
		img: 'images/goods/triangle1_5.jpg',
		price: 1200,
	},
	{
		id: 't16',
		name: 'Прямоугольный треугольник',
		color: 'Синий',
		img: 'images/goods/triangle1_6.jpg',
		price: 1200,
	},
	{
		id: 't17',
		name: 'Прямоугольный треугольник',
		color: 'Фиолетовый',
		img: 'images/goods/triangle1_7.jpg',
		price: 1200,
	},
	{
		id: 't21',
		name: 'Равносторонний треугольник',
		color: 'Белый',
		img: 'images/goods/triangle2_1.jpg',
		price: 2100,
	},
	{
		id: 't22',
		name: 'Равносторонний треугольник',
		color: 'Красный',
		img: 'images/goods/triangle2_2.jpg',
		price: 2100,
	},
	{
		id: 't23',
		name: 'Равносторонний треугольник',
		color: 'Желтый',
		img: 'images/goods/triangle2_3.jpg',
		price: 2100,
	},
	{
		id: 't24',
		name: 'Равносторонний треугольник',
		color: 'Зеленый',
		img: 'images/goods/triangle2_4.jpg',
		price: 2100,
	},
	{
		id: 't25',
		name: 'Равносторонний треугольник',
		color: 'Голубой',
		img: 'images/goods/triangle2_5.jpg',
		price: 2100,
	},
	{
		id: 't26',
		name: 'Равносторонний треугольник',
		color: 'Синий',
		img: 'images/goods/triangle2_6.jpg',
		price: 2100,
	},
	{
		id: 't27',
		name: 'Равносторонний треугольник',
		color: 'Фиолетовый',
		img: 'images/goods/triangle2_7.jpg',
		price: 2100,
	},
	{
		id: 't31',
		name: 'Равнобедренный треугольник',
		color: 'Белый',
		img: 'images/goods/triangle3_1.jpg',
		price: 2100,
	},
	{
		id: 't32',
		name: 'Равнобедренный треугольник',
		color: 'Красный',
		img: 'images/goods/triangle3_2.jpg',
		price: 2100,
	},
	{
		id: 't33',
		name: 'Равнобедренный треугольник',
		color: 'Желтый',
		img: 'images/goods/triangle3_3.jpg',
		price: 2100,
	},
	{
		id: 't34',
		name: 'Равнобедренный треугольник',
		color: 'Зеленый',
		img: 'images/goods/triangle3_4.jpg',
		price: 2100,
	},
	{
		id: 't35',
		name: 'Равнобедренный треугольник',
		color: 'Голубой',
		img: 'images/goods/triangle3_5.jpg',
		price: 2100,
	},
	{
		id: 't36',
		name: 'Равнобедренный треугольник',
		color: 'Синий',
		img: 'images/goods/triangle3_6.jpg',
		price: 2100,
	},
	{
		id: 't37',
		name: 'Равнобедренный треугольник',
		color: 'Фиолетовый',
		img: 'images/goods/triangle3_7.jpg',
		price: 2100,
	},
	{
		id: 't41',
		name: 'Разносторонний треугольник',
		color: 'Белый',
		img: 'images/goods/triangle4_1.jpg',
		price: 3000,
	},
	{
		id: 't42',
		name: 'Разносторонний треугольник',
		color: 'Красный',
		img: 'images/goods/triangle4_2.jpg',
		price: 3000,
	},
	{
		id: 't43',
		name: 'Разносторонний треугольник',
		color: 'Желтый',
		img: 'images/goods/triangle4_3.jpg',
		price: 3000,
	},
	{
		id: 't44',
		name: 'Разносторонний треугольник',
		color: 'Зеленый',
		img: 'images/goods/triangle4_4.jpg',
		price: 3000,
	},
	{
		id: 't45',
		name: 'Разносторонний треугольник',
		color: 'Голубой',
		img: 'images/goods/triangle4_5.jpg',
		price: 3000,
	},
	{
		id: 't46',
		name: 'Разносторонний треугольник',
		color: 'Синий',
		img: 'images/goods/triangle4_6.jpg',
		price: 3000,
	},
	{
		id: 't47',
		name: 'Разносторонний треугольник',
		color: 'Фиолетовый',
		img: 'images/goods/triangle4_7.jpg',
		price: 3000,
	},
	{
		id: 'q11',
		name: 'Квадрат',
		color: 'Белый',
		img: 'images/goods/Quadrilateral1_1.jpg',
		price: 400,
	},
	{
		id: 'q12',
		name: 'Квадрат',
		color: 'Красный',
		img: 'images/goods/Quadrilateral1_2.jpg',
		price: 400,
	},
	{
		id: 'q13',
		name: 'Квадрат',
		color: 'Желтый',
		img: 'images/goods/Quadrilateral1_3.jpg',
		price: 400,
	},
	{
		id: 'q14',
		name: 'Квадрат',
		color: 'Зеленый',
		img: 'images/goods/Quadrilateral1_4.jpg',
		price: 400,
	},
	{
		id: 'q15',
		name: 'Квадрат',
		color: 'Голубой',
		img: 'images/goods/Quadrilateral1_5.jpg',
		price: 400,
	},
	{
		id: 'q16',
		name: 'Квадрат',
		color: 'Синий',
		img: 'images/goods/Quadrilateral1_6.jpg',
		price: 400,
	},
	{
		id: 'q17',
		name: 'Квадрат',
		color: 'Фиолетовый',
		img: 'images/goods/Quadrilateral1_7.jpg',
		price: 400,
	},
	{
		id: 'q21',
		name: 'Прямоугольник',
		color: 'Белый',
		img: 'images/goods/Quadrilateral2_1.jpg',
		price: 400,
	},
	{
		id: 'q22',
		name: 'Прямоугольник',
		color: 'Красный',
		img: 'images/goods/Quadrilateral2_2.jpg',
		price: 400,
	},
	{
		id: 'q23',
		name: 'Прямоугольник',
		color: 'Желтый',
		img: 'images/goods/Quadrilateral2_3.jpg',
		price: 400,
	},
	{
		id: 'q24',
		name: 'Прямоугольник',
		type: 'quadrilateral',
		variety: 'rectangle',
		color: 'Зеленый',
		corners: 4,
		img: 'images/goods/Quadrilateral2_4.jpg',
		price: 400,
	},
	{
		id: 'q25',
		name: 'Прямоугольник',
		color: 'Голубой',
		img: 'images/goods/Quadrilateral2_5.jpg',
		price: 400,
	},
	{
		id: 'q26',
		name: 'Прямоугольник',
		color: 'Синий',
		img: 'images/goods/Quadrilateral2_6.jpg',
		price: 400,
	},
	{
		id: 'q27',
		name: 'Прямоугольник',
		color: 'Фиолетовый',
		img: 'images/goods/Quadrilateral2_7.jpg',
		price: 400,
	},
	{
		id: 'q31',
		name: 'Ромб',
		color: 'Белый',
		img: 'images/goods/Quadrilateral3_1.jpg',
		price: 4000,
	},
	{
		id: 'q32',
		name: 'Ромб',
		color: 'Красный',
		img: 'images/goods/Quadrilateral3_2.jpg',
		price: 4000,
	},
	{
		id: 'q33',
		name: 'Ромб',
		color: 'Желтый',
		img: 'images/goods/Quadrilateral3_3.jpg',
		price: 4000,
	},
	{
		id: 'q34',
		name: 'Ромб',
		color: 'Зеленый',
		img: 'images/goods/Quadrilateral3_4.jpg',
		price: 4000,
	},
	{
		id: 'q35',
		name: 'Ромб',
		color: 'Голубой',
		img: 'images/goods/Quadrilateral3_5.jpg',
		price: 4000,
	},
	{
		id: 'q36',
		name: 'Ромб',
		color: 'Синий',
		img: 'images/goods/Quadrilateral3_6.jpg',
		price: 4000,
	},
	{
		id: 'q37',
		name: 'Ромб',
		color: 'Фиолетовый',
		img: 'images/goods/Quadrilateral3_7.jpg',
		price: 2200,
	},
	{
		id: 'q41',
		name: 'Параллелограмм',
		color: 'Белый',
		img: 'images/goods/Quadrilateral4_1.jpg',
		price: 2200,
	},
	{
		id: 'q42',
		name: 'Параллелограмм',
		color: 'Красный',
		img: 'images/goods/Quadrilateral4_2.jpg',
		price: 2200,
	},
	{
		id: 'q43',
		name: 'Параллелограмм',
		color: 'Желтый',
		img: 'images/goods/Quadrilateral4_3.jpg',
		price: 2200,
	},
	{
		id: 'q44',
		name: 'Параллелограмм',
		color: 'Зеленый',
		img: 'images/goods/Quadrilateral4_4.jpg',
		price: 2200,
	},
	{
		id: 'q45',
		name: 'Параллелограмм',
		color: 'Голубой',
		img: 'images/goods/Quadrilateral4_5.jpg',
		price: 2200,
	},
	{
		id: 'q46',
		name: 'Параллелограмм',
		color: 'Синий',
		img: 'images/goods/Quadrilateral4_6.jpg',
		price: 2200,
	},
	{
		id: 'q47',
		name: 'Параллелограмм',
		color: 'Фиолетовый',
		img: 'images/goods/Quadrilateral4_7.jpg',
		price: 2200,
	},
	{
		id: 'p11',
		name: 'Пятиугольник',
		color: 'Белый',
		img: 'images/goods/polygon1_1.jpg',
		price: 4100,
	},
	{
		id: 'p12',
		name: 'Пятиугольник',
		color: 'Красный',
		img: 'images/goods/polygon1_2.jpg',
		price: 4100,
	},
	{
		id: 'p13',
		name: 'Пятиугольник',
		color: 'Желтый',
		img: 'images/goods/polygon1_3.jpg',
		price: 4100,
	},
	{
		id: 'p14',
		name: 'Пятиугольник',
		color: 'Зеленый',
		img: 'images/goods/polygon1_4.jpg',
		price: 4100,
	},
	{
		id: 'p15',
		name: 'Пятиугольник',
		color: 'Голубой',
		img: 'images/goods/polygon1_5.jpg',
		price: 4100,
	},
	{
		id: 'p16',
		name: 'Пятиугольник',
		color: 'Синий',
		img: 'images/goods/polygon1_6.jpg',
		price: 4100,
	},
	{
		id: 'p17',
		name: 'Пятиугольник',
		color: 'Фиолетовый',
		img: 'images/goods/polygon1_7.jpg',
		price: 4100,
	},
	{
		id: 'p21',
		name: 'Шестиугольник',
		color: 'Белый',
		img: 'images/goods/polygon2_1.jpg',
		price: 4200,
	},
	{
		id: 'p22',
		name: 'Шестиугольник',
		color: 'Красный',
		img: 'images/goods/polygon2_2.jpg',
		price: 4200,
	},
	{
		id: 'p23',
		name: 'Шестиугольник',
		color: 'Желтый',
		img: 'images/goods/polygon2_3.jpg',
		price: 4200,
	},
	{
		id: 'p24',
		name: 'Шестиугольник',
		color: 'Зеленый',
		img: 'images/goods/polygon2_4.jpg',
		price: 4200,
	},
	{
		id: 'p25',
		name: 'Шестиугольник',
		color: 'Голубой',
		img: 'images/goods/polygon2_5.jpg',
		price: 4200,
	},
	{
		id: 'p26',
		name: 'Шестиугольник',
		color: 'Синий',
		img: 'images/goods/polygon2_6.jpg',
		price: 4200,
	},
	{
		id: 'p27',
		name: 'Шестиугольник',
		color: 'Фиолетовый',
		img: 'images/goods/polygon2_7.jpg',
		price: 4200,
	},
	{
		id: 'p31',
		name: 'Звезда',
		color: 'Белый',
		img: 'images/goods/polygon3_1.jpg',
		price: 9900,
	},
	{
		id: 'p32',
		name: 'Звезда',
		color: 'Красный',
		img: 'images/goods/polygon3_2.jpg',
		price: 9900,
	},
	{
		id: 'p33',
		name: 'Звезда',
		color: 'Желтый',
		img: 'images/goods/polygon3_3.jpg',
		price: 9900,
	},
	{
		id: 'p34',
		name: 'Звезда',
		color: 'Зеленый',
		img: 'images/goods/polygon3_4.jpg',
		price: 9900,
	},
	{
		id: 'p35',
		name: 'Звезда',
		color: 'Голубой',
		img: 'images/goods/polygon3_5.jpg',
		price: 9900,
	},
	{
		id: 'p36',
		name: 'Звезда',
		color: 'Синий',
		img: 'images/goods/polygon3_6.jpg',
		price: 9900,
	},
	{
		id: 'p37',
		name: 'Звезда',
		color: 'Фиолетовый',
		img: 'images/goods/polygon3_7.jpg',
		price: 9900,
	},
	{
		id: 'e11',
		name: 'Элипс',
		color: 'Белый',
		img: 'images/goods/ellipse1_1.jpg',
		price: 10100,
	},
	{
		id: 'e12',
		name: 'Элипс',
		color: 'Красный',
		img: 'images/goods/ellipse1_2.jpg',
		price: 10100,
	},
	{
		id: 'e13',
		name: 'Элипс',
		color: 'Желтый',
		img: 'images/goods/ellipse1_3.jpg',
		price: 10100,
	},
	{
		id: 'e14',
		name: 'Элипс',
		color: 'Зеленый',
		img: 'images/goods/ellipse1_4.jpg',
		price: 10100,
	},
	{
		id: 'e15',
		name: 'Элипс',
		color: 'Голубой',
		img: 'images/goods/ellipse1_5.jpg',
		price: 10100,
	},
	{
		id: 'e16',
		name: 'Элипс',
		color: 'Синий',
		img: 'images/goods/ellipse1_6.jpg',
		price: 10100,
	},
	{
		id: 'e17',
		name: 'Элипс',
		color: 'Фиолетовый',
		img: 'images/goods/ellipse1_7.jpg',
		price: 10100,
	},
	{
		id: 'e21',
		name: 'Круг',
		color: 'Белый',
		img: 'images/goods/ellipse2_1.jpg',
		price: 10000,
	},
	{
		id: 'e22',
		name: 'Круг',
		color: 'Красный',
		img: 'images/goods/ellipse2_2.jpg',
		price: 10000,
	},
	{
		id: 'e23',
		name: 'Круг',
		color: 'Желтый',
		img: 'images/goods/ellipse2_3.jpg',
		price: 10000,
	},
	{
		id: 'e24',
		name: 'Круг',
		color: 'Зеленый',
		img: 'images/goods/ellipse2_4.jpg',
		price: 10000,
	},
	{
		id: 'e25',
		name: 'Круг',
		color: 'Голубой',
		img: 'images/goods/ellipse2_5.jpg',
		price: 10000,
	},
	{
		id: 'e26',
		name: 'Круг',
		color: 'Синий',
		img: 'images/goods/ellipse2_6.jpg',
		price: 10000,
	},
	{
		id: 'e27',
		name: 'Круг',
		color: 'Фиолетовый',
		img: 'images/goods/ellipse2_7.jpg',
		price: 10000,
	},
];